Vagrant.configure("2") do |config|
config.vm.define :servidor do |servidor|
servidor.vm.box = "bento/centos-7.9"
servidor.vm.network :private_network, ip: "192.168.50.3"
servidor.vm.network "forwarded_port", guest: 80, host: 8080
servidor.vm.hostname = "servidor"
servidor.vm.synced_folder "./backup", "/servidor", id: "vagrant-root2",
      owner: "vagrant",
      group: "vagrant",
      mount_options: ["uid=1234", "gid=1234"]   
end
config.vm.define :cliente do |cliente|
cliente.vm.box = "bento/centos-7.9"
cliente.vm.network :private_network, ip: "192.168.50.2"
cliente.vm.hostname = "cliente"
cliente.vm.synced_folder "./backup", "/cliente", id: "vagrant-root1",
      owner: "vagrant",
      group: "vagrant",
      mount_options: ["uid=1234", "gid=1234"]
end
end
